#!/usr/bin/env python3

"""
Fetch KEGG Orthology (KO) definitions for a list of KO IDs.

This script takes a file containing KO IDs as input, fetches their definitions from the KEGG database,
and saves the results to a CSV file. The output file name is generated by replacing '_list.txt' in the
input file name with '_definitions.txt'.

Usage:
    python fetch_ko_definitions.py <ko_ids_file>

Arguments:
    <ko_ids_file> : Path to the input file containing KO IDs, one per line.

Outputs:
    A CSV file containing the following columns:
        - KEGG_ko: The KO ID
        - ko_name: The name of the KO
        - ko_symbol: The symbol of the KO (if available)

Example:
    python fetch_ko_definitions.py ko_ids_list.txt
"""

import requests
import pandas as pd
import sys
import argparse

def main():
    parser = argparse.ArgumentParser(
        description="Fetch KEGG Orthology (KO) definitions for a list of KO IDs."
    )
    parser.add_argument(
        "--ko-list",
        required=True,
        help="Path to the input file containing KO IDs, one per line."
    )
    args = parser.parse_args()

    # Read the input file containing ko_ids
    ko_ids_file = args.ko_list
    try:
        with open(ko_ids_file, 'r') as f:
            ko_ids = [line.strip() for line in f.readlines()]
    except FileNotFoundError:
        print(f"Error: File '{ko_ids_file}' not found.")
        sys.exit(1)

    # Initialize an empty list to store module data
    ko_data = []

    # Loop through each module ID and fetch its definition
    for ko_id in ko_ids:
        url = f"https://rest.kegg.jp/get/ko:{ko_id}"
        response = requests.get(url)
        
        if response.status_code == 200:
            # Parse the module definition
            ko_info = {}
            for line in response.text.splitlines():
                if line.startswith("ENTRY"):
                    ko_info["ENTRY"] = line.split()[1]
                elif line.startswith("SYMBOL"):
                    ko_info["SYMBOL"] = line[12:].strip()  # Extract the symbol
                elif line.startswith("NAME"):
                    ko_info["NAME"] = line[12:].strip()  # Extract the name
            
            # Add the parsed module info to the list
            ko_data.append(ko_info)
        else:
            print(f"Failed to fetch module {ko_id}. Status code: {response.status_code}")

    # Convert the list of module data into a DataFrame
    ko_df = pd.DataFrame(ko_data)
    ko_df.rename(columns={"ENTRY": "KEGG_ko", "NAME": "ko_name", "SYMBOL": "ko_symbol"}, inplace=True)

    # Save the DataFrame to a CSV file
    # Generate the output filename by replacing '_list.txt' with 'definitions.txt'
    output_file = ko_ids_file.replace('_list.txt', '_definitions.txt')
    ko_df.to_csv(output_file, index=False)
    print(f"Data saved to {output_file}")

    # Print the DataFrame
    print(ko_df.head())

if __name__ == "__main__":
    main()
